version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "grpc-app_v1.0"
    environment:
      - GRPC_ADDR=:9003
      - HTTP_ADDR=:8003
      - PG_PORT=5432
    restart: on-failure
    ports:
      - "9003:9003"
      - "8003:8003"
    depends_on:
      - postgres-db
    networks:
      - learning

  migrate:
    build: scheme/.
    restart: on-failure
    depends_on:
      - postgres-db
    networks:
      - learning

  postgres-db:
    image: postgres:latest
    container_name: "grpc-app-db_v1.0"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres-db
    networks:
      - learning

networks:
  learning:
    driver: bridge
